### ISSUE TITLE
Multiple author support

### ISSUE THREAD

**Issue by hbaniecki** [g1eny0ung/hugo-theme-dream#138]
Will there be support for multiple blog authors? E.g. with two containers for two people.
I have found (allegedly) such option in https://github.com/UtkarshVerma/hugo-dream-plus, but it's not being updated.

**Comment by g1eny0ung** [comment]
You mean multiple authors in the front matter? Like:

```yaml
---
authors:
  - author1
  - author2
---
```

**Comment by hbaniecki** [comment]
It would be neat to have two author pages and be able to link each of them to blog posts.
![image](https://user-images.githubusercontent.com/32574004/88146013-98435200-cbfb-11ea-8348-8d4d96bf7d1d.png)

**Comment by g1eny0ung** [comment]
Seems it's difficult to implement this feature.

This means that you need to regenerate some pages with completely different data, not only posts but also pages similar to social links, post categories, etc.

But I thought of a compromise. I can set a param `authorlink` in the front matter of the post so that you can jump to another author's site by clicking the name on the summary card.

![image](https://user-images.githubusercontent.com/15034155/88148516-47e6e700-cc31-11ea-894f-529898ee30db.png)

All you need is to generate two sites with the same theme.

**Comment by hbaniecki** [comment]
Sure, that is creative. After all, I only propose a feature to consider. Unfortunate that it's difficult to implement.

**Comment by g1eny0ung** [comment]
Thanks for the suggestion. I will add the `authorlink` param soonly to help to cite other authors' articles.
