### ISSUE TITLE
[Feature Request] Youtube previews as cover images.

### ISSUE THREAD

**Issue by Sp-cy** [g1eny0ung/hugo-theme-dream#145]
Hello! 

1.- Is it possible to use youtube video previews as cover images? Right now i copy the static image thumbnail that youtube generates for it's site and use it as cover image but everything would look much cleaner if it was just the video with a description. 
 2.- Can the icon for Mastodon be added to the fonts file?
3.- If you add a tweet preview iframe to a post, the preview card may not resize to the card making it look bigger than the post tile. 

![image](https://user-images.githubusercontent.com/68587155/92745472-07117180-f348-11ea-95a2-f263f415ccdc.png)

I'm not sure how this could be adjusted. Since i'm guessing it's an issue with the tweet shortcode. 

Love your theme, Thanks for your work and help.

**Comment by g1eny0ung** [comment]
A little confused about the second point. Can you describe it in more detail?

**Comment by Sp-cy** [comment]
[Mastodon](https://mastodon.social/about) is a new social network, i can't find the logo in the brand's font file. It's moderately popular.

**Comment by g1eny0ung** [comment]
Know about it, I have already added the mastodon icon.

You can config it as:

```toml
[params]
  mastodon = ""
```

The first question, because the youtube animated preview is `.webp` file and it won't be fully supported in modern browsers, so I still recommend u to use its static thumbnail.

For the third question, after I researched, I found that it's difficult to make a twitter widget card responsive because it will insert an iframe with a different origin. The js can't access the iframe contents due to the Same-origin policy.

The width of the card is limit in the range [250, 550]px. You can view more details in https://developer.twitter.com/en/docs/twitter-for-websites/embedded-tweets/guides/embedded-tweet-parameter-reference.

But I still optimized its display a bit (within my ability), at least it won't overflow now. And for performance considerations, you also need to set a parameter:

```toml
[params]
  hasTwitterEmbed = true
```

After setting this, you can safely remove the async script(`<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>`) in the generated code.

**Comment by Sp-cy** [comment]
Thank you for your time and knowledge.  I am grateful for your help.
