### ISSUE TITLE
Reduced Mobile View 

### ISSUE THREAD

**Issue by Sp-cy** [g1eny0ung/hugo-theme-dream#147]
Hello g1eny0ung. I am learning HUGO and web dev with your theme because it was one of the best documented, has multilingual support and it looks good too! I've been having a couple of issues and questions in which I hope you can help me and or guide me.

1. When viewing the site from a mobile phone the grid column with and the grid container padding size make the area of the content to be reduced which is causing the words in the content files to be cut in my languaje when displayed in the grid but not in the specific view of that site. **Can the text in the homepage behave identical to the post page formatting?** 

2. Another similar issue is happening with **emoji** where they **are not displaying in the grid but they do in the post view** as visible in the screenshots. 

3. Dates are having a similar problem where they don't display in some posts and in others it's in english instead of spanish in the case of my site. 

---

These are more Feature Requests and questions than issues:
 
- Can a site params be added to control de grid tightness or column with? Or how can this be done in the theme files? I understand that this can change the theme and you may not want to implement but since I don't know web development I'm lost about how to do this properly. 

- How should i change the reading minutes area at the bottom of the post container in the homepage to display the post's tags instead just like in the post view? 

- What does the showcase feature in the front matter do? I couldn't find any reference in the documentation and i'm not sure if you removed it in recent updates. 

Sorry for the extensive post, I hope you can guide me and I hope you have a good day! 

Edit: Removed picture overload. And the social sharing cards in 4 are not a problem anymore. I'll update on that later.

**Comment by Sp-cy** [comment]
I think the date display problems have to do with missing translations, checking on my data/es.toml and everything seems to be in order. But still every post made in a "Sunday" or "Domingo" is not displaying the day and some other days display the english value in the post view which it is default behavior in HUGO for missing dates.

**Comment by g1eny0ung** [comment]
Sorry for the late reply. These days are China's National Day holiday, and I'm still on vacation. I'll try to solve all the problems after the holiday because I didn't bring the computer with me.😂

**Comment by Sp-cy** [comment]
Oh no problem! I'm reading and trying to figure whatever I can on my own. Enjoy your vacations! Happy Holiday!

**Comment by g1eny0ung** [comment]
@Sp-cy

The following fixes can be found in this commit 7158682.

> When viewing the site from a mobile phone the grid column with and the grid container padding size make the area of the content to be reduced which is causing the words in the content files to be cut in my languaje when displayed in the grid but not in the specific view of that site. Can the text in the homepage behave identical to the post page formatting?

This problem should be the wrong use of a CSS style: `word-break: break-all;`. I will change it to `overflow-wrap: break-word;`. Maybe this can solve this problem.

ref: https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap

> Another similar issue is happening with emoji where they are not displaying in the grid but they do in the post view as visible in the screenshots.

If you are using the text format of emoji, this problem has been solved.

ref: https://gohugo.io/functions/emojify

> Dates are having a similar problem where they don't display in some posts and in others it's in english instead of spanish in the case of my site.

Could you provide me an example? It is difficult to reproduce this problem.

But after testing, I found an error. The Sunday of `.Date.Weekday` should be index 0 instead of index 7. I have fixed this problem in translations.

> Can a site params be added to control de grid tightness or column with? Or how can this be done in the theme files? I understand that this can change the theme and you may not want to implement but since I don't know web development I'm lost about how to do this properly.

It can be done. The current tightness you can found in https://github.com/g1eny0ung/hugo-theme-dream/blob/master/layouts/index.html#L10.

Just change the `wide`. The docs of the grid system are https://semantic-ui.com/collections/grid.html#manual-tweaks.

> How should i change the reading minutes area at the bottom of the post container in the homepage to display the post's tags instead just like in the post view?

It's very easy. just copy `{{ .ReadingTime }}{{ i18n "minuteRead" }}` in the `summary.html` to anywhere you want.

> What does the showcase feature in the front matter do? I couldn't find any reference in the documentation and i'm not sure if you removed it in recent updates.

This was an experimental feature. Its function is to double the size of the grid summary. Like this:

![image](https://user-images.githubusercontent.com/15034155/95671849-e9952900-0bcd-11eb-958e-ce9fdc73fece.png)

But I have removed it because I think it occupies a large area and will affect the overall page layout.

**Comment by Sp-cy** [comment]
thank you for your time and knowledge. I'm checking and reading those documentation links. Most of the issues I stated seem to have been fixed so I'm closing this.

**Comment by Sp-cy** [comment]
I do love your experimental feature. It's a good idea.

**Comment by g1eny0ung** [comment]
> I do love your experimental feature. It's a good idea.

I will consider adding it back.
