### ISSUE TITLE
Active fork

### ISSUE THREAD

**Issue by Darthagnon** [g1eny0ung/hugo-theme-dream#275]
## [Here is my active fork of Dream](https://github.com/Darthagnon/hugo-theme-dream)

I'm a bit ADHD, and still a bit of a noob with git, so commits tend to be a bit "all or nothing". Pull requests welcome; as I actively use it on my homepage, development is ongoing.

Maybe eventually we can merge back into this master branch.

**Comment by Darthagnon** [comment]
Some features have been added, though I'm not planning on rewriting the theme in Bulma.

**Comment by g1eny0ung** [comment]
> Some features have been added (see [production branch](https://github.com/Darthagnon/hugo-theme-dream/tree/production)), though I'm not planning on rewriting the theme in Bulma.

Sounds good.~ I've already reopened the unresolved issues that are marked as stale. I didn't finish rewriting this in Bulma. I unknowingly forgot about it, and it was not finished with a bang...

> I'm a bit ADHD, and still a bit of a noob with git, so commits tend to be a bit "all or nothing". Pull requests welcome; as I actively use it on my homepage, development is ongoing.

> Maybe eventually we can merge back into this master branch.

The best way is to split out the different features, but I remember before you put a lot of features in one PR. This made it more difficult to merge because it was hard to get focus from many features (Refer to Unix philosophy, **make each program do one thing well** ⛑️).

Starting tomorrow is Chinese New Year and I won't start working on it right away, but after a week I'll gradually start reviewing some of the previous issues. Again, thanks for your work! 💯
