### ISSUE TITLE
Question: more default (random) covers possible ?

### ISSUE THREAD

**Issue by MarcusE1W** [g1eny0ung/hugo-theme-dream#6]
Hi @g1eny0ung.

A great theme, thanks for creating this.

I have a question. I like that the default covers are getting randomly assigned to the articles on the main page.
Is it possible to add more cover images that get randomly assigned?

I have see the parameter in the front matter to assign a specific image to a specific article, but is it possible to keep the random assinment with my own pictures ?

**Comment by g1eny0ung** [comment]
There is no possible to random your own pictures only with Hugo. Because each article's summary was ordered by the article's date (from the newest to oldest).

If there is no set `cover` parameter in your article.md, the summary image will set as:

```
{{ if isset .Params "cover" }}
<img src="{{ .Params.cover }}" alt="{{ .Title }}">
{{ else }}
<img src="/img/default{{ index (shuffle (seq 1 6)) 0 }}.jpg" alt="{{ .Title }}">
{{ end }}
```

Shuffle a sequence, like `1 2 3 4 5 6` => `2 5 1 6 4 3`, then get the first(index 0), at last it will render `/img/default2.jpg`.

Currently, it only has 3 default images in the `themes/hugo-dream-theme/static/img` folder, I will add more to 6 default images later.

**But all of these images are not dynamic random**. Hugo is a static site generator. When you deploy your site, each page will be changeless.

**Comment by MarcusE1W** [comment]
Thanks for the quick reply. Will try this out.
